env:
- param=$$value
image: google/debian:wheezy
publish:
  docker:
    docker_server: $$docker_server
    email: $$docker_email
    image_name: mohit/temp-container
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: some-branch
script:
- make test
- make build
services:
- mongo:2.6
